config/routes.rb
Rails.application.routes.draw do
  root "page#home"

  get "index" => "page#home"

  devise_for :users

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  namespace :admin do
    root "cards#index"

    resources :cards, only: [:index, :edit, :update] do
      member do
        post :move_higher
        post :move_lower
      end
    end

    resources :publish, only: [:create]

    resources :users, except: [:show]
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
  EMBED_LINK_REGEX = /\Ahttps?:\/\/(www\.)?(youtube\.com|youtu\.be|vimeo\.com)\//

  acts_as_list

  validates :link, presence: true, format: {with: EMBED_LINK_REGEX, message: "is not a valid video link"}
  validates :description, presence: true

  has_attached_file :background, styles: {
    thumb: ["200x200#", :png],
    small: ["400x300#", :jpg],
    big: ["800x600#", :jpg]
  }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :background, content_type: /\Aimage\/.*\Z/

  scope :sorted, ->{ order(position: :asc) }

  def title
    if description.present?
      description.gsub("\n", " ")
    end
  end

end

app/models/ftp_uploader.rb
class FtpUploader
  attr_reader :username, :host, :password, :files

  def initialize(host, username=nil, password=nil)
    @host = host
    @username = username
    @password = password

    @files = []
  end

  def add(file, path, opts={})
    @files << FtpUploadFile.new(file, path, binary: !!opts[:binary])
  end

  def upload
    log "Starting upload of #{ @files.count } files"
    raise "Host must be set" if host.blank?

    ftp = Net::FTP.new(@host, @username, @password)
    log ftp.inspect

    @files.each do |file|
      log "Processing #{ file.inspect }"

      ftp.chdir("~")

      begin
        log "Changing to path #{ file.path }"
        ftp.chdir(file.path)
        log "Path found"
      rescue Net::FTPPermError => e
        log "Path not found", e

        file.segments.each do |segment|
          begin
            log "Changing to path segment '#{ segment }'"
            ftp.chdir(segment)
            log "Path segment found"
          rescue Net::FTPPermError => ee
            log "Path segment not found", ee
            log "Creating path '#{ segment }'"
            ftp.mkdir(segment)
            log "Changing to created path segment '#{ segment }'"
            ftp.chdir(segment)
          end
        end
      end

      log "Currently working in #{ ftp.pwd }"

      if file.binary
        log "Uploading binary file #{ file.file } => #{ file.filename }"
        ftp.putbinaryfile(file.file, file.filename)
      else
        log "Uploading text file #{ file.file } => #{ file.filename }"
        ftp.puttextfile(file.file, file.filename)
      end

      log "Finished processing #{ file.inspect }"
    end

    log "Upload finished"

    ftp.close

    @files = []
  end

  def inspect
    "#<FtpUploader host:#{ host } username:#{ username } password:#{ password.present? ? "*****" : "" } pending_files:#{ @files.count }>"
  end

  private

  def log(message, exception=nil)
    Rails.logger.info("[#{ self.class.name }] #{ message } #{ exception.try(:message) ? ": #{ exception.message }" : "" }")
  end

  class FtpUploadFile
    attr_reader :file, :binary, :filename, :segments

    def initialize(file, target, opts={})
      file = File.new(file) if file.is_a?(String)

      @file = file
      @target = target
      @binary = !!opts[:binary]

      @segments = @target.split(File::SEPARATOR).reject(&:blank?)
      @filename = @segments.pop
    end

    def path
      segments.join("/")
    end
  end

end

app/models/page_renderer.rb
class PageRenderer
  def home
    ApplicationController.new.render_to_string(
      template: 'page/home',
      layout: 'application',
      locals: { :@cards => cards }
    )
  end

  def home_assets
    cards.map do |card|
      card.background
    end
  end

  private

  def cards
    @cards ||= Card.sorted
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
         # :confirmable, :lockable, :timeoutable, :omniauthable, :registerable

  validates :name, presence: true

end

app/controllers/admin/cards_controller.rb
class Admin::CardsController < AdminController
  before_action :load_card, only: [:edit, :update, :move_higher, :move_lower]

  def index
    @cards = Card.sorted
  end

  def edit
  end

  def update
    if @card.update(card_params)
      redirect_to admin_cards_path, notice: 'Update successful.'
    else
      render :edit
    end
  end

  def move_higher
    @card.move_higher unless @card.first?
    redirect_to admin_cards_path
  end

  def move_lower
    @card.move_lower unless @card.last?
    redirect_to admin_cards_path
  end

  private

  def load_card
    @card = Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:description, :link, :background)
  end
end

app/controllers/admin/publish_controller.rb
class Admin::PublishController < AdminController

  def create
    begin
      PublishJob.perform_later(user_id: current_user.id)

      redirect_to admin_root_path, notice: "Site has been published"
    rescue => e
      Rails.logger.error("Failed to publish")
      Rails.logger.error(e)
      Rails.logger.error(e.backtrace.join("\n"))

      redirect_to admin_root_path, flash: { error: "There was a problem publishing the site. If it persists, contact the site admin. Error: #{ e.message }" }
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    if user_params[:password].present?
      if @user.update(user_params)
        redirect_to admin_users_path, notice: 'User and and password were successfully updated.'
      else
        render :edit
      end
    else
      if @user.update_without_password(user_params)
        redirect_to admin_users_path, notice: 'User was successfully updated.'
      else
        render :edit
      end
    end
  end

  def destroy
    if @user == current_user
      flash[:error] = 'You cannot delete yourself.'
    else
      @user.destroy
      flash[:notice] = 'User was successfully destroyed.'
    end

    redirect_to admin_users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
  before_action :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def after_sign_in_path_for(resource)
    admin_root_path
  end
end

app/controllers/page_controller.rb
class PageController < PublicController
  def home
    @cards = Card.sorted
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  skip_before_filter :verify_authenticity_token
end

app/helpers/admin_helper.rb
module AdminHelper
  def error_messages(form)
    render "shared/error_messages", object: form.object if form.object.errors.any?
  end

  def card_image_preview(card, opts={})
    opts = {alt: card.title, style: "width: 200px; height: 200px; margin: 10px;", class: "img-thumbnail"}.merge(opts)

    image_tag(card.background.url(:thumb), opts)
  end

  def higher_arrow_for_index(index)
    case index
    when 0, 2, 3, 5
      "up"
    when 1
      "left"
    when 4
      "right"
    end
  end

  def lower_arrow_for_index(index)
    case index
    when 1, 2, 4, 5
      "down"
    when 3
      "left"
    when 0
      "right"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper

  def class_for_index(index)
    case index % 6
    when 0
      "big"
    when 1, 2
      "small"
    when 3
      "big2"
    when 4, 5
      "small2"
    end
  end

  def card_image_size(index)
    case index % 6
    when 0, 3
      :big
    when 1, 2, 4, 5
      :small
    end
  end

end

app/views/admin/cards/_card_index.html.erb
<% if card %>
  <%= link_to card_image_preview(card), edit_admin_card_path(card), class: "pull-left" %>
  <p style="padding-top: 10px">
    <%= link_to card.title, edit_admin_card_path(card) %>
  </p>
  <div class="btn-group">
    <%= link_to edit_admin_card_path(card), class: "btn btn-default" do %>
      <i class="fa fa-pencil-square-o fa-lg"></i> Edit
    <% end %>
    <% unless card.first? %>
      <%= link_to move_higher_admin_card_path(card), method: :post, class: "btn btn-default" do %>
        <i class="fa fa-arrow-<%= higher_arrow_for_index(index) %> fa-lg"></i>
      <% end %>
    <% end %>
    <% unless card.last? %>
      <%= link_to move_lower_admin_card_path(card), method: :post, class: "btn btn-default" do %>
        <i class="fa fa-arrow-<%= lower_arrow_for_index(index) %> fa-lg"></i>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/admin/cards/_form.html.erb
<%= form_for([:admin, @card]) do |f| %>
  <%= error_messages(f) %>

  <div class="form-group">
    <%= f.label :description, "Description text" %>
    <%= f.text_area :description, class: "form-control", rows: 5, cols: 40 %>
    <!-- <p class="help-block">Accepts multiple lines</p> -->
  </div>

  <div class="form-group">
    <%= f.label :link, "YouTube link" %>
    <%= f.text_field :link, class: "form-control", size: 50, placeholder: "http://youtube.com/watch" %>
  </div>

  <div class="form-group">
    <%= f.label :background, "Background image" %>
    <%= f.file_field :background, class: "form-control", onchange: "previewImage(this, 'image_preview');" %>
    <%= card_image_preview @card, id: "image_preview" %>
  </div>

  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to 'Back', admin_cards_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/admin/cards/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/admin/cards/index.html.erb
<h1>Manage Main Page</h1>

<table class="table table-bordered">
  <% @cards.each_slice(6) do |cards| %>
    <tr>
      <td colspan="2" rowspan="2">
        <%= render "card_index", card: cards[0], index: 0 %>
      </td>
      <td colspan="2">
        <%= render "card_index", card: cards[1], index: 1 %>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <%= render "card_index", card: cards[2], index: 2 %>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <%= render "card_index", card: cards[4], index: 4 %>
      </td>
      <td colspan="2" rowspan="2">
        <%= render "card_index", card: cards[3], index: 3 %>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <%= render "card_index", card: cards[5], index: 5 %>
      </td>
    </tr>

  <% end %>
</table>

app/views/admin/users/_form.html.erb
<%= form_for([:admin, @user]) do |f| %>
  <%= error_messages(f) %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: "User's name" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control", placeholder: "example@10kislands.com" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control", placeholder: "Password", autocomplete: "off" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password", autocomplete: "off" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to 'Back', admin_users_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>
  <% if @user == current_user %>
    Edit Yourself
  <% else %>
    Edit User
  <% end %>
</h1>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>Manage Users</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td class="text-right">
          <% unless user == current_user %>
            <%= link_to admin_user_path(user), class: "btn btn-mini btn-danger", method: :delete, data: { confirm: 'Are you sure you want to remove this user?' } do %>
              <i class="fa fa-trash-o fa-lg"></i> Delete
            <% end %>
          <% end %>
          <%= link_to edit_admin_user_path(user), class: "btn btn-mini btn-default" do %>
            <i class="fa fa-pencil-square-o fa-lg"></i> Edit
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to new_admin_user_path, class: "btn btn-primary" do %>
  <i class="fa fa-user fa-lg"></i> Add New User
<% end %>

app/views/admin/users/new.html.erb
<h1>Add New User</h1>

<%= render 'form' %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "10K Islands" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "admin", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon" />
    <link rel="icon" href="images/favicon.png" type="image/x-icon" />

    <%= javascript_include_tag "admin" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">10K Islands</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <% if current_user %>
            <ul class="nav navbar-nav">
              <li>
                <%= link_to "Home Page", admin_root_path %>
              </li>
              <li>
                <%= link_to "Manage Users", admin_users_path %>
              </li>
              <li>
                <%= link_to admin_publish_index_path, method: :post, data: { confirm: "Do you want to publish the site?" } do %>
                  <i class="fa fa-external-link-square fa-lg"></i>
                  Publish site
                <% end %>
              </li>
            </ul>
            <ul class="nav navbar-nav pull-right">
              <li>
              <%= link_to "Support", "http://kevinmcphillips.ca" %>
              </li>
              <li>
                <%= link_to "Logout", logout_path %>
              </li>
            </ul>
          <% else %>
            <ul class="nav navbar-nav pull-right">
              <li>
              <%= link_to "Support", "http://kevinmcphillips.ca" %>
              </li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>

      <footer>
      </footer>

    </div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="shortcut icon" href="images/favicon.png" type="image/x-icon" />
<link rel="icon" href="images/favicon.png" type="image/x-icon" />

<title>10K ISLANDS</title>

<link rel="stylesheet" type="text/css" href="MyFontsWebfontsKit.css">
<link rel="stylesheet" type="text/css" href="MyFontsWebfontsKit2.css">

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

<script>
$(function() {
$('a[href*=#]:not([href=#])').click(function() {
if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {

var target = $(this.hash);
target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
if (target.length) {
$('html,body').animate({
scrollTop: target.offset().top
}, 1000);
return false;
}
}
});
});
</script>






<script type="text/javascript">
$(document).ready(function(){
	$('#page_effect').fadeIn(2000);
});

$(document).ready(function() {

    // Hide the div
    $("#downarrow").hide();

    // Show the div in 5s
    $("#downarrow").delay(2000).fadeIn(000);

});
</script>

<script type="text/javascript">

$(document).ready(function(){
    $('#downarrow').animate({
        'marginTop' : "+=80px" //moves down
        });
});

</script>





<link rel="stylesheet" href="css/prettyPhoto.css" type="text/css" media="screen" title="prettyPhoto main stylesheet" charset="utf-8" />
<script src="js/jquery.prettyPhoto.js" type="text/javascript" charset="utf-8"></script>


<link href="css/common.css" rel="stylesheet" type="text/css" />
<link href="css/responsive.css" rel="stylesheet" type="text/css" />


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= Rails.application.secrets.google_analytics %>', 'auto');
  ga('send', 'pageview');

</script>

</head>

<body>


<!-- Top Band Starts -->

<div class="top-band">

<div class="logo"><a href="index.html"><img src="images/logo.svg" border="0" /></a></div>

<div class="top-navigation">
<a href="studio.html" >Studio</a>
<a href="info.html" >Info</a>
<a href="https://open.spotify.com/user/10k_islands" target="_blank" class="spotify">Spotify</a>
</div>


</div>

<!-- Top Band Ends -->







<div class="clear"></div>







<!-- Home Part-1 Starts-->

<div class="home-part-1">
<div class="downn-arrow" id="downarrow"  ><a href="#second"><img src="images/down-arrow.png" /></a></div>
<table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center" valign="middle"><a href="#second"><img src="images/dot.png" class="logo-shadow" /></a></td>
  </tr>
</table>




</div>

<!-- Home Part-1 Ends-->



<div class="clear"></div>

<a name="second" id="second"></a>
<%= yield %>


<div class="clear"></div>












<!-- Footer Starts-->

<div class="footer-box">
<div class="footer-box3">© 2014 10K Islands. All rights reserved. </div>
<div class="footer-box1"><a href="mailto:info@10kislands.com" target="_blank">info@10kislands.com</a></div>
<div class="footer-box2">
<a href="https://www.facebook.com/10kislands" target="_blank"><img src="images/social-icon2.png" /></a>
<a href="http://instagram.com/10kislands" target="_blank"><img src="images/social-icon3.png" /></a>
<a href="https://soundcloud.com/10kislands" target="_blank"><img src="images/social-icon4.png" /></a>
<a href="https://www.youtube.com/user/10kislandsmusic" target="_blank"><img src="images/social-icon5.png" /></a>
<a href="https://twitter.com/10kislands" target="_blank"><img src="images/social-icon1.png" /></a>
</div>
</div>
<!-- Footer Ends-->





<script type="text/javascript" charset="utf-8">
$(document).ready(function(){
    $("area[rel^='prettyPhoto']").prettyPhoto();

    $(".gallery:first a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'normal',theme:'light_square',slideshow:3000, autoplay_slideshow: true});
    $(".gallery:gt(0) a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'fast',slideshow:10000, hideflash: true});

    $("#custom_content a[rel^='prettyPhoto']:first").prettyPhoto({
        custom_markup: '<div id="map_canvas" style="width:260px; height:265px"></div>',
        changepicturecallback: function(){ initialize(); }
    });

    $("#custom_content a[rel^='prettyPhoto']:last").prettyPhoto({
        custom_markup: '<div id="bsap_1259344" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6"></div><div id="bsap_1237859" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6" style="height:260px"></div><div id="bsap_1251710" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6"></div>',
        changepicturecallback: function(){ _bsap.exec(); }
    });
});
</script>



</body>
</html>

app/views/page/_card.html.erb
<div class="<%= class_for_index(index) %>" <%= 'style="display: none"'.html_safe if local_assigns[:hidden] %>>
  <div class="gallery clearfix">
    <%= link_to card.link, rel: "prettyPhoto" do %>
      <span>
        <%= simple_format(card.description) %>
      </span>
      <%= image_tag card.background.url(card_image_size(index)), alt: card.title %>
    <% end %>
  </div>
</div>

app/views/page/home.html.erb
<div class="home-part-2">
  <%= render "page/card", card: @cards.first, index: 1, hidden: true %>

  <% @cards.each_with_index do |card, index| %>
    <%= render "page/card", card: card, index: index %>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<div id="error_explanation" class="alert fade in alert-danger">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <h4>Aww dang... There were <%= pluralize(object.errors.count, "error") %> when saving</h4>

  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>